data:
  raw_dir: "/app/data/raw"
  processed_dir: "/app/data/processed"
  filenames:
    - "genome-scores.csv"
    - "genome-tags.csv"
    - "links.csv"
    - "movies.csv"
    - "ratings.csv"
    - "README.txt"
    - "tags.csv"
  bucket_url: "https://mlops-project-db.s3.eu-west-1.amazonaws.com/movie_recommandation/"

make_dataset:
  input_dir: "/app/data/raw"
  output_dir: "/app/data/processed"

features:
    ratings_file: "ratings.csv"
    movies_file: "movies.csv"

model:
  model_dir: "/app/models"
  model_filename: "best_svd_model.pkl"
  n_neighbors: 20  # Pour KNNBasic si utilisé
  processed_data_dir: "/app/data/processed"
  sample_size: 500_000
  train_sample_size: 1_000_000

predict:
  processed_data_dir: "/app/data/processed"
  model_dir: "/app/models"
  predictions_dir: "/app/predictions"
  metrics_dir: "/app/metrics"
  users_id: [1]  # liste d'utilisateurs pour la prédiction
  top_N: 5
  predict_sample_size: 2_000_000

mlflow:
  tracking_uri: "http://mlflow:5000"
  experiment_name: "movie_recommendation"

db:
  dbname: reco_films
  user: reco_films
  password: reco_films
  host: db  # Nom du service dans docker-compose.yml
  port: 5432

